config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

analysis-paths:
- analysis
clean-targets:
- ../.meltano/transformers/dbt/target
- dbt_packages
- logs
seed-paths:
- data
log-path: logs
macro-paths:
- macros
models:
  my_meltano_project: null
  tap_gitlab:
    vars:
      schema: '{{ env_var(''MELTANO_LOAD_SCHEMA'') }}'
      ultimate_license: '{{ env_var(''GITLAB_API_ULTIMATE_LICENSE'', False) }}'
packages-install-path: dbt_packages
name: my_meltano_project
profile: meltano
snapshot-paths:
- snapshots
model-paths:
- models
target-path: ../.meltano/transformers/dbt/target
test-paths:
- tests
version: '1.0'
